name: CI/CD automation
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  CI:
    runs-on: ubuntu-latest # specify the build machine
    steps:
      # Clone our code into runner
      - name: Checkout
        uses: actions/checkout@v3
      
      # Build the Docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: express:latest
          outputs: type=docker,dest=${{ runner.temp }}/express.tar   
          
      # Run Container using Image (Test)
      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/express.tar
          docker image ls -a
      - name: Create Container using image
        run: docker run -d -p 3000:3000 express
        
      # Upload Image so it can be used by others job (CD)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: ${{ runner.temp }}/express.tar

  CD:
    runs-on: ubuntu-latest # specify the build machine
    needs: CI
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: express
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/express.tar
          docker image ls -a
          
      - name: Create Container using image
        run: |
          docker load --input ${{ runner.temp }}/express.zip
          docker image ls -a
          docker run -d -p 3000:3000 express

      

